// Turns tokens/tokens.json into src/tokens.css:
//   1. --gm-* CSS variables (light, dark via prefers-color-scheme, and [data-theme] overrides)
//   2. a Tailwind v4 `@theme inline` block mapping utilities (bg-primary, rounded-md, ...) to them
// Arabic pages (html[lang="ar"]) switch the sans font to the Arabic stack automatically.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));

const lines = (entries) => entries.map(([k, v]) => `  ${k}: ${v};`).join("\n");
const colors = Object.entries(tokens.color);
const light = colors.map(([name, v]) => [`--gm-color-${name}`, v.light]);
const dark = colors.map(([name, v]) => [`--gm-color-${name}`, v.dark]);
const statics = [
  ...Object.entries(tokens.radius).map(([k, v]) => [`--gm-radius-${k}`, v]),
  ...Object.entries(tokens.font).map(([k, v]) => [`--gm-font-${k}`, v]),
  ...Object.entries(tokens.shadow).map(([k, v]) => [`--gm-shadow-${k}`, v]),
];
const theme = [
  ...colors.map(([name]) => [`--color-${name}`, `var(--gm-color-${name})`]),
  ...Object.keys(tokens.radius).map((k) => [`--radius-${k}`, `var(--gm-radius-${k})`]),
  ["--font-sans", "var(--gm-font-active)"],
  ["--font-mono", "var(--gm-font-mono)"],
  ...Object.keys(tokens.shadow).map((k) => [`--shadow-${k}`, `var(--gm-shadow-${k})`]),
];

const css = `/* GENERATED by packages/ui/scripts/build-tokens.mjs from tokens/tokens.json. Do not edit. */
:root {
${lines([...light, ...statics, ["--gm-font-active", "var(--gm-font-sans)"]])}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${lines(dark).replace(/^/gm, "  ")}
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
${lines(dark)}
  color-scheme: dark;
}
:root[lang="ar"] {
  --gm-font-active: var(--gm-font-arabic);
}
@theme inline {
${lines(theme)}
}
`;

writeFileSync(join(root, "src/tokens.css"), css);
console.log(`tokens.css written (${colors.length} colors)`);
