/**
 * Visitor-facing UI text. Restaurant content comes translated from the database; these are the
 * labels around it. Languages without a UI translation yet fall back to English labels.
 */
const en = {
  menu: "Menu",
  go: "GO",
  goTitle: "Get directions",
  chooseBranch: "Choose a branch",
  share: "Share",
  shareWhatsapp: "Share on WhatsApp",
  copied: "Link copied",
  openNow: "Open now",
  closedNow: "Closed now",
  hours: "Opening hours",
  closed: "Closed",
  branches: "Our branches",
  gallery: "Gallery",
  contact: "Contact",
  call: "Call",
  whatsapp: "WhatsApp",
  email: "Email",
  soldOut: "Sold out",
  from: "from {price}",
  calories: "{n} kcal",
  allergens: "Allergens",
  dietary: "Dietary",
  spice: ["Not spicy", "Mild", "Medium", "Hot"],
  options: "Options",
  choose: "Choose {min}–{max}",
  chooseUpTo: "Choose up to {max}",
  optional: "Optional",
  required: "Required",
  back: "Back",
  viewItem: "View",
  allBranches: "All branches",
  branch: "Branch",
  language: "Language",
  signIn: "Sign in",
  myAccount: "My account",
  favorite: "Save to favorites",
  unfavorite: "Remove from favorites",
  table: "Table {label}",
  tableNote: "You scanned the QR code at table {label}.",
  promotions: "Offers",
  until: "Until {date}",
  frames: "Today",
  close: "Close",
  next: "Next",
  previous: "Previous",
  about: "About us",
  unavailableTitle: "{name} is temporarily unavailable",
  unavailableBody: "This website is offline for now. Please check back soon.",
  previewBanner: "Preview: only people who manage this website can see this.",
  poweredBy: "Powered by GoMenu",
  orderingSoon: "Online ordering is coming soon.",
  days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  allergenNames: {
    gluten: "Gluten", crustaceans: "Crustaceans", eggs: "Eggs", fish: "Fish", peanuts: "Peanuts", soybeans: "Soy",
    milk: "Milk", tree_nuts: "Tree nuts", celery: "Celery", mustard: "Mustard", sesame: "Sesame",
    sulphites: "Sulphites", lupin: "Lupin", molluscs: "Molluscs",
  } as Record<string, string>,
  dietaryNames: {
    vegetarian: "Vegetarian", vegan: "Vegan", halal: "Halal", gluten_free: "Gluten-free", dairy_free: "Dairy-free",
    nut_free: "Nut-free", healthy: "Healthy", new: "New", popular: "Popular", chef_special: "Chef's special",
  } as Record<string, string>,
};

export type SiteStrings = typeof en;

const ar: SiteStrings = {
  menu: "القائمة",
  go: "انطلق",
  goTitle: "احصل على الاتجاهات",
  chooseBranch: "اختر الفرع",
  share: "مشاركة",
  shareWhatsapp: "مشاركة عبر واتساب",
  copied: "تم نسخ الرابط",
  openNow: "مفتوح الآن",
  closedNow: "مغلق الآن",
  hours: "ساعات العمل",
  closed: "مغلق",
  branches: "فروعنا",
  gallery: "معرض الصور",
  contact: "تواصل معنا",
  call: "اتصال",
  whatsapp: "واتساب",
  email: "البريد",
  soldOut: "نفدت الكمية",
  from: "ابتداءً من {price}",
  calories: "{n} سعرة",
  allergens: "مسببات الحساسية",
  dietary: "النظام الغذائي",
  spice: ["غير حار", "خفيف", "متوسط", "حار"],
  options: "الخيارات",
  choose: "اختر {min}–{max}",
  chooseUpTo: "اختر حتى {max}",
  optional: "اختياري",
  required: "مطلوب",
  back: "رجوع",
  viewItem: "عرض",
  allBranches: "كل الفروع",
  branch: "الفرع",
  language: "اللغة",
  signIn: "تسجيل الدخول",
  myAccount: "حسابي",
  favorite: "أضف إلى المفضلة",
  unfavorite: "أزل من المفضلة",
  table: "طاولة {label}",
  tableNote: "لقد مسحت رمز QR على الطاولة {label}.",
  promotions: "العروض",
  until: "حتى {date}",
  frames: "اليوم",
  close: "إغلاق",
  next: "التالي",
  previous: "السابق",
  about: "من نحن",
  unavailableTitle: "{name} غير متاح مؤقتاً",
  unavailableBody: "هذا الموقع متوقف حالياً. يرجى العودة لاحقاً.",
  previewBanner: "معاينة: لا يراها إلا من يدير هذا الموقع.",
  poweredBy: "مدعوم من GoMenu",
  orderingSoon: "الطلب عبر الإنترنت قريباً.",
  days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
  allergenNames: {
    gluten: "الغلوتين", crustaceans: "القشريات", eggs: "البيض", fish: "السمك", peanuts: "الفول السوداني", soybeans: "الصويا",
    milk: "الحليب", tree_nuts: "المكسرات", celery: "الكرفس", mustard: "الخردل", sesame: "السمسم",
    sulphites: "الكبريتات", lupin: "الترمس", molluscs: "الرخويات",
  },
  dietaryNames: {
    vegetarian: "نباتي", vegan: "نباتي صرف", halal: "حلال", gluten_free: "خالٍ من الغلوتين", dairy_free: "خالٍ من الألبان",
    nut_free: "خالٍ من المكسرات", healthy: "صحي", new: "جديد", popular: "الأكثر طلباً", chef_special: "اختيار الشيف",
  },
};

export function siteStrings(locale: string): SiteStrings {
  return locale === "ar" ? ar : en;
}

/** Intl locale for numbers and dates in this site language. */
export function intlLocale(locale: string): string {
  return ({ ar: "ar-OM", en: "en-GB", fr: "fr-FR", ur: "ur-PK", hi: "hi-IN", fa: "fa-IR" } as Record<string, string>)[locale] ?? "en-GB";
}
