/**
 * Visitor-facing UI text. Restaurant content comes translated from the database; these are the
 * labels around it. Languages without a UI translation yet fall back to English labels.
 */
const en = {
  menu: "Menu",
  go: "GO",
  goTitle: "Get directions",
  chooseBranch: "Choose a branch",
  share: "Share",
  shareWhatsapp: "Share on WhatsApp",
  copied: "Link copied",
  openNow: "Open now",
  closedNow: "Closed now",
  hours: "Opening hours",
  closed: "Closed",
  branches: "Our branches",
  gallery: "Gallery",
  contact: "Contact",
  call: "Call",
  whatsapp: "WhatsApp",
  email: "Email",
  soldOut: "Sold out",
  from: "from {price}",
  calories: "{n} kcal",
  allergens: "Allergens",
  dietary: "Dietary",
  spice: ["Not spicy", "Mild", "Medium", "Hot"],
  options: "Options",
  choose: "Choose {min}–{max}",
  chooseUpTo: "Choose up to {max}",
  optional: "Optional",
  required: "Required",
  back: "Back",
  viewItem: "View",
  allBranches: "All branches",
  branch: "Branch",
  language: "Language",
  signIn: "Sign in",
  myAccount: "My account",
  favorite: "Save to favorites",
  unfavorite: "Remove from favorites",
  table: "Table {label}",
  tableNote: "You scanned the QR code at table {label}.",
  promotions: "Offers",
  until: "Until {date}",
  frames: "Today",
  close: "Close",
  next: "Next",
  previous: "Previous",
  about: "About us",
  unavailableTitle: "{name} is temporarily unavailable",
  unavailableBody: "This website is offline for now. Please check back soon.",
  previewBanner: "Preview: only people who manage this website can see this.",
  poweredBy: "Powered by GoMenu",
  order: {
    add: "Add to order",
    added: "Added to your order",
    quantity: "Quantity",
    decrease: "Fewer",
    increase: "More",
    notes: "Notes for the kitchen (optional)",
    chooseSize: "Size",
    viewOrder: "View order",
    items: "{n} items",
    oneItem: "1 item",
    yourOrder: "Your order",
    empty: "Your order is empty.",
    backToMenu: "Back to the menu",
    remove: "Remove",
    howToGet: "How do you want it?",
    serviceTable: "At my table",
    serviceTableHint: "Scan the QR code on your table to order to it.",
    serviceCar: "To my car",
    servicePickup: "Pickup",
    carPlate: "Car plate",
    carDescription: "Car colour and model (optional)",
    name: "Your name",
    phone: "Mobile number (optional)",
    orderNotes: "Notes (optional)",
    subtotal: "Subtotal",
    vatIncluded: "Includes VAT {rate}%",
    vatAdded: "VAT {rate}%",
    total: "Total",
    estimate: "The restaurant's current prices are confirmed when you place the order.",
    payAfter: "You pay at the end.",
    payBefore: "You pay before we start preparing.",
    place: "Place order",
    placing: "Placing your order…",
    order: "Order #{n}",
    status: "Status",
    steps: {
      placed: "Placed", waiting: "Waiting for confirmation", confirmed: "Confirmed", preparing: "Preparing",
      ready: "Ready", served: "Served", completed: "Completed",
      rejected: "Not accepted", cancelled: "Cancelled", refunded: "Refunded",
    } as Record<string, string>,
    rejected: "The restaurant could not accept this order.",
    cancelled: "This order was cancelled.",
    refunded: "This order was refunded.",
    payment: "Payment",
    paymentStatus: {
      unpaid: "Not paid yet", pending: "Payment in progress", paid: "Paid", failed: "Payment failed — please try again",
      partially_refunded: "Partly refunded", refunded: "Refunded",
    } as Record<string, string>,
    payNow: "Pay now",
    payWaitConfirm: "You can pay online once the restaurant confirms your order.",
    payAtRestaurant: "Pay the staff when you are ready.",
    cancel: "Cancel order",
    cancelConfirm: "Cancel this order?",
    live: "This page updates by itself.",
    myOrders: "My orders",
    signInToSave: "Sign in to keep your orders in your account.",
    errors: {
      ORDERING_OFF: "This restaurant is not taking online orders right now.",
      ITEM_UNAVAILABLE: "Something in your order is no longer available. Please remove it and try again.",
      VARIANT_UNAVAILABLE: "A size you chose is no longer available.",
      OPTION_UNAVAILABLE: "An option you chose is no longer available.",
      OPTIONS_REQUIRED: "Please choose the required options.",
      BRANCH_CLOSED: "This branch is closed right now.",
      BRANCH_REQUIRED: "Please choose a branch.",
      PLATE_REQUIRED: "Please enter your car plate.",
      TABLE_NEEDS_QR: "Scan the QR code on your table to order to it.",
      QR_INVALID: "This table's QR code is no longer active. Please ask the staff.",
      SERVICE_OFF: "This option is not available.",
      EMPTY_ORDER: "Your order is empty.",
      NOT_PAYABLE: "This order cannot be paid online now.",
      TOO_LATE: "This order can no longer be cancelled here; please ask the staff.",
      PHONE_INVALID: "Enter a valid mobile number, for example +968 9123 4567.",
      generic: "Something went wrong. Please try again.",
    } as Record<string, string>,
  },
  days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  allergenNames: {
    gluten: "Gluten", crustaceans: "Crustaceans", eggs: "Eggs", fish: "Fish", peanuts: "Peanuts", soybeans: "Soy",
    milk: "Milk", tree_nuts: "Tree nuts", celery: "Celery", mustard: "Mustard", sesame: "Sesame",
    sulphites: "Sulphites", lupin: "Lupin", molluscs: "Molluscs",
  } as Record<string, string>,
  dietaryNames: {
    vegetarian: "Vegetarian", vegan: "Vegan", halal: "Halal", gluten_free: "Gluten-free", dairy_free: "Dairy-free",
    nut_free: "Nut-free", healthy: "Healthy", new: "New", popular: "Popular", chef_special: "Chef's special",
  } as Record<string, string>,
};

export type SiteStrings = typeof en;

const ar: SiteStrings = {
  menu: "القائمة",
  go: "انطلق",
  goTitle: "احصل على الاتجاهات",
  chooseBranch: "اختر الفرع",
  share: "مشاركة",
  shareWhatsapp: "مشاركة عبر واتساب",
  copied: "تم نسخ الرابط",
  openNow: "مفتوح الآن",
  closedNow: "مغلق الآن",
  hours: "ساعات العمل",
  closed: "مغلق",
  branches: "فروعنا",
  gallery: "معرض الصور",
  contact: "تواصل معنا",
  call: "اتصال",
  whatsapp: "واتساب",
  email: "البريد",
  soldOut: "نفدت الكمية",
  from: "ابتداءً من {price}",
  calories: "{n} سعرة",
  allergens: "مسببات الحساسية",
  dietary: "النظام الغذائي",
  spice: ["غير حار", "خفيف", "متوسط", "حار"],
  options: "الخيارات",
  choose: "اختر {min}–{max}",
  chooseUpTo: "اختر حتى {max}",
  optional: "اختياري",
  required: "مطلوب",
  back: "رجوع",
  viewItem: "عرض",
  allBranches: "كل الفروع",
  branch: "الفرع",
  language: "اللغة",
  signIn: "تسجيل الدخول",
  myAccount: "حسابي",
  favorite: "أضف إلى المفضلة",
  unfavorite: "أزل من المفضلة",
  table: "طاولة {label}",
  tableNote: "لقد مسحت رمز QR على الطاولة {label}.",
  promotions: "العروض",
  until: "حتى {date}",
  frames: "اليوم",
  close: "إغلاق",
  next: "التالي",
  previous: "السابق",
  about: "من نحن",
  unavailableTitle: "{name} غير متاح مؤقتاً",
  unavailableBody: "هذا الموقع متوقف حالياً. يرجى العودة لاحقاً.",
  previewBanner: "معاينة: لا يراها إلا من يدير هذا الموقع.",
  poweredBy: "مدعوم من GoMenu",
  order: {
    add: "أضف إلى الطلب",
    added: "تمت الإضافة إلى طلبك",
    quantity: "الكمية",
    decrease: "أقل",
    increase: "أكثر",
    notes: "ملاحظات للمطبخ (اختياري)",
    chooseSize: "الحجم",
    viewOrder: "عرض الطلب",
    items: "{n} أصناف",
    oneItem: "صنف واحد",
    yourOrder: "طلبك",
    empty: "طلبك فارغ.",
    backToMenu: "العودة إلى القائمة",
    remove: "إزالة",
    howToGet: "كيف تريد استلامه؟",
    serviceTable: "على طاولتي",
    serviceTableHint: "امسح رمز QR على طاولتك للطلب إليها.",
    serviceCar: "إلى سيارتي",
    servicePickup: "استلام",
    carPlate: "رقم السيارة",
    carDescription: "لون السيارة وطرازها (اختياري)",
    name: "اسمك",
    phone: "رقم الهاتف (اختياري)",
    orderNotes: "ملاحظات (اختياري)",
    subtotal: "المجموع الفرعي",
    vatIncluded: "شامل ضريبة القيمة المضافة {rate}٪",
    vatAdded: "ضريبة القيمة المضافة {rate}٪",
    total: "الإجمالي",
    estimate: "يتم تأكيد الأسعار الحالية للمطعم عند إرسال الطلب.",
    payAfter: "تدفع في النهاية.",
    payBefore: "تدفع قبل أن نبدأ التحضير.",
    place: "أرسل الطلب",
    placing: "جارٍ إرسال طلبك…",
    order: "طلب رقم {n}",
    status: "الحالة",
    steps: {
      placed: "تم الإرسال", waiting: "بانتظار التأكيد", confirmed: "تم التأكيد", preparing: "قيد التحضير",
      ready: "جاهز", served: "تم التقديم", completed: "مكتمل",
      rejected: "لم يُقبل", cancelled: "ملغى", refunded: "مسترد",
    },
    rejected: "لم يتمكن المطعم من قبول هذا الطلب.",
    cancelled: "تم إلغاء هذا الطلب.",
    refunded: "تم استرداد مبلغ هذا الطلب.",
    payment: "الدفع",
    paymentStatus: {
      unpaid: "لم يتم الدفع بعد", pending: "الدفع قيد التنفيذ", paid: "مدفوع", failed: "فشل الدفع — يرجى المحاولة مجدداً",
      partially_refunded: "مسترد جزئياً", refunded: "مسترد",
    },
    payNow: "ادفع الآن",
    payWaitConfirm: "يمكنك الدفع عبر الإنترنت بعد أن يؤكد المطعم طلبك.",
    payAtRestaurant: "ادفع للموظفين عندما تكون جاهزاً.",
    cancel: "إلغاء الطلب",
    cancelConfirm: "هل تريد إلغاء هذا الطلب؟",
    live: "تتحدث هذه الصفحة تلقائياً.",
    myOrders: "طلباتي",
    signInToSave: "سجّل الدخول لحفظ طلباتك في حسابك.",
    errors: {
      ORDERING_OFF: "هذا المطعم لا يستقبل الطلبات عبر الإنترنت حالياً.",
      ITEM_UNAVAILABLE: "أحد أصناف طلبك لم يعد متاحاً. يرجى إزالته والمحاولة مجدداً.",
      VARIANT_UNAVAILABLE: "الحجم الذي اخترته لم يعد متاحاً.",
      OPTION_UNAVAILABLE: "أحد الخيارات التي اخترتها لم يعد متاحاً.",
      OPTIONS_REQUIRED: "يرجى اختيار الخيارات المطلوبة.",
      BRANCH_CLOSED: "هذا الفرع مغلق الآن.",
      BRANCH_REQUIRED: "يرجى اختيار الفرع.",
      PLATE_REQUIRED: "يرجى إدخال رقم السيارة.",
      TABLE_NEEDS_QR: "امسح رمز QR على طاولتك للطلب إليها.",
      QR_INVALID: "رمز QR لهذه الطاولة لم يعد فعالاً. يرجى سؤال الموظفين.",
      SERVICE_OFF: "هذا الخيار غير متاح.",
      EMPTY_ORDER: "طلبك فارغ.",
      NOT_PAYABLE: "لا يمكن دفع هذا الطلب عبر الإنترنت الآن.",
      TOO_LATE: "لم يعد بالإمكان إلغاء هذا الطلب من هنا؛ يرجى سؤال الموظفين.",
      PHONE_INVALID: "أدخل رقم هاتف صحيحاً، مثل ‎+968 9123 4567.",
      generic: "حدث خطأ ما. يرجى المحاولة مجدداً.",
    },
  },
  days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
  allergenNames: {
    gluten: "الغلوتين", crustaceans: "القشريات", eggs: "البيض", fish: "السمك", peanuts: "الفول السوداني", soybeans: "الصويا",
    milk: "الحليب", tree_nuts: "المكسرات", celery: "الكرفس", mustard: "الخردل", sesame: "السمسم",
    sulphites: "الكبريتات", lupin: "الترمس", molluscs: "الرخويات",
  },
  dietaryNames: {
    vegetarian: "نباتي", vegan: "نباتي صرف", halal: "حلال", gluten_free: "خالٍ من الغلوتين", dairy_free: "خالٍ من الألبان",
    nut_free: "خالٍ من المكسرات", healthy: "صحي", new: "جديد", popular: "الأكثر طلباً", chef_special: "اختيار الشيف",
  },
};

export function siteStrings(locale: string): SiteStrings {
  return locale === "ar" ? ar : en;
}

/** Intl locale for numbers and dates in this site language. */
export function intlLocale(locale: string): string {
  return ({ ar: "ar-OM", en: "en-GB", fr: "fr-FR", ur: "ur-PK", hi: "hi-IN", fa: "fa-IR" } as Record<string, string>)[locale] ?? "en-GB";
}
