-- Phase 4: structured analytics events (spec §14; reports come in Phase 7) and the diner account
-- (spec §12: one universal identity; Phase 4 covers profile, preferences, favorites, privacy).

create type public.analytics_event_type as enum (
  'website_view', 'menu_view', 'item_view', 'frame_view', 'frame_complete', 'frame_click',
  'promotion_view', 'promotion_click', 'qr_scan', 'go_click', 'share_click'
);

create table public.analytics_events (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants (id) on delete restrict,
  branch_id uuid,
  event_type public.analytics_event_type not null,
  entity_id uuid,
  qr_code_id uuid references public.qr_codes (id),
  session_id text check (session_id is null or session_id ~ '^[A-Za-z0-9_-]{8,64}$'),
  user_id uuid references auth.users (id) on delete set null,
  locale text,
  -- Staff and platform activity is excluded from production analytics (spec §14).
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);
create index analytics_events_restaurant_idx on public.analytics_events (restaurant_id, created_at desc);
create index analytics_events_session_idx on public.analytics_events (session_id, created_at desc);
create trigger tenant_write_guard before insert or update or delete on public.analytics_events
  for each row execute function private.guard_tenant_writable();

alter table public.analytics_events enable row level security;
alter table public.analytics_events force row level security;
revoke all on public.analytics_events from anon, authenticated;
grant select on public.analytics_events to authenticated;
create policy analytics_events_select on public.analytics_events for select to authenticated
  using ((select private.has_permission(restaurant_id, 'analytics.view')));

-- Diner privacy controls live on the shared profile.
alter table public.profiles
  add column analytics_opt_out boolean not null default false,
  add column marketing_opt_in boolean not null default false;
grant update (analytics_opt_out, marketing_opt_in) on public.profiles to authenticated;

-- Events come only through this function: validated, rate-limited, anonymous unless signed in.
create or replace function public.track_event(
  p_restaurant_id uuid,
  p_event_type public.analytics_event_type,
  p_session_id text default null,
  p_entity_id uuid default null,
  p_branch_id uuid default null,
  p_qr_code_id uuid default null,
  p_locale text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if not private.restaurant_publicly_available(p_restaurant_id) then
    return;
  end if;
  if p_session_id is not null and p_session_id !~ '^[A-Za-z0-9_-]{8,64}$' then
    return;
  end if;
  -- At most 120 events per session per minute; extra events are dropped silently.
  if p_session_id is not null and (select count(*) from public.analytics_events
       where session_id = p_session_id and created_at > now() - interval '1 minute') >= 120 then
    return;
  end if;
  if p_branch_id is not null and not exists (select 1 from public.branches where id = p_branch_id and restaurant_id = p_restaurant_id) then
    p_branch_id := null;
  end if;
  if p_qr_code_id is not null and not exists (select 1 from public.qr_codes where id = p_qr_code_id and restaurant_id = p_restaurant_id) then
    p_qr_code_id := null;
  end if;
  insert into public.analytics_events (restaurant_id, branch_id, event_type, entity_id, qr_code_id, session_id,
                                       user_id, locale, is_internal)
  values (p_restaurant_id, p_branch_id, p_event_type, p_entity_id, p_qr_code_id, p_session_id,
          case when v_uid is not null and not coalesce((select analytics_opt_out from public.profiles where id = v_uid), false)
               then v_uid end,
          left(p_locale, 8),
          v_uid is not null and (private.is_platform_staff()
                                 or exists (select 1 from public.memberships where user_id = v_uid and restaurant_id = p_restaurant_id)));
end;
$$;

-- Favorites: a diner's own list of restaurants and dishes. Restaurants can't read it.
create table public.diner_favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  restaurant_id uuid not null references public.restaurants (id) on delete cascade,
  item_id uuid,
  created_at timestamptz not null default now(),
  foreign key (item_id, restaurant_id) references public.menu_items (id, restaurant_id) on delete cascade
);
create unique index diner_favorites_restaurant_uidx on public.diner_favorites (user_id, restaurant_id) where item_id is null;
create unique index diner_favorites_item_uidx on public.diner_favorites (user_id, item_id) where item_id is not null;
create trigger tenant_write_guard before insert or update or delete on public.diner_favorites
  for each row execute function private.guard_tenant_writable();

alter table public.diner_favorites enable row level security;
alter table public.diner_favorites force row level security;
revoke all on public.diner_favorites from anon, authenticated;
grant select, insert, delete on public.diner_favorites to authenticated;
create policy diner_favorites_own on public.diner_favorites for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()) and (select private.restaurant_publicly_available(restaurant_id)));

-- "Delete my diner data": favorites and preferences. (Orders arrive in Phase 5 and are kept as
-- restaurant records; erasure there needs the retention policy noted in the README.)
create or replace function public.delete_my_diner_data()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  -- Only the caller's own rows are touched; a suspended restaurant must not block this.
  perform set_config('gomenu.system_action', 'on', true);
  delete from public.diner_favorites where user_id = auth.uid();
  update public.analytics_events set user_id = null where user_id = auth.uid();
  update public.profiles set marketing_opt_in = false where id = auth.uid();
  perform set_config('gomenu.system_action', 'off', true);
end;
$$;

grant execute on function private.restaurant_publicly_available(uuid) to authenticated;
grant execute on function public.track_event(uuid, public.analytics_event_type, text, uuid, uuid, uuid, text) to anon, authenticated;
grant execute on function public.delete_my_diner_data() to authenticated;
